default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  port: 3306

development:
  <<: *default
  host: db
  database: myapp_development
  password: password

test:
  <<: *default
  host: db
  database: myapp_test
  password: password

production:
  <<: *default
  database: myapp_prouction
  url: <%= Rails.application.credentials.production.database_url %>

production:
  # この行はYAMLのアンカー機能を使用しています。'*default'は他の場所で定義されたデフォルト設定をこのセクションにマージすることを意味します。つまり、本番環境の設定はデフォルト設定をベースにし、下記の設定でオーバーライドされます。
  <<: *default

  # 本番用データベースの名前を設定します。ここでの名前 'myapp_prouction' はおそらく 'myapp_production' のタイプミスです。正しくは 'myapp_production' であるべきです。
  database: myapp_production

  # この行は、Railsの暗号化されたクレデンシャル機能を使って、データベースのURLを設定します。Rails.application.credentials.production.database_url は、本番環境用のデータベース接続情報（例えば、ホスト名、ポート番号、ユーザー名、パスワードなど）を含むURLを指します。この情報は安全に管理され、コード内で直接露出することはありません。
  url: <%= Rails.application.credentials.production.database_url %>

# 下記、デフォルトで書かれている情報
# default: &default
#   adapter: mysql2
#   encoding: utf8mb4
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password:
#   host: localhost

# development:
#   <<: *default
#   database: myapp_development

# test:
#   <<: *default
#   database: myapp_test

# production:
#   <<: *default
#   database: myapp_production
#   username: myapp
#   password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
